version: 2

project_name: jawt

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: jawt
    main: ./cmd/jawt/
    binary: jawt
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    # This handles your requirement: zip for windows, tar.gz for others
    formats:
      - tar.gz
      - zip

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: alessandrocaglio
    name: jawt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# dockers_v2:
#   - id: katalog
#     images:
#       - "quay.io/acaglio/jawt"
#     tags:
#       - "{{ .Tag }}"
#       - latest
#     platforms:
#       - linux/amd64
#       - linux/arm64
#     dockerfile: Containerfile